# -*- coding: utf-8 -*-
"""pandas-py.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/tolaramkewatiya-hub/60619869651bceb405f88af8aba62f25/pandas-py.ipynb
"""

import numpy as np
import pandas as pd

import numpy as np
import pandas as pd
dict1 = {
    "name":['harry','rohan','mohan','raghu'],
    "marks":[92,37,28,44],
    "city":['jaipur','jodhpur','churu','pakistan'],

}
df = pd.DataFrame(dict1)
df
df.to_csv('friends.csv')
df.to_csv('friends_index_false.csv',index=False)
df.head()
df.tail()
df.describe()
harry = pd.read_csv('friends.csv')
harry
harry['marks']
harry['marks'][0] = 60
harry
harry.to_csv('harry.csv')
harry.to_csv('harry_index_False.csv',index=False)
harry = pd.read_csv('harry.csv')
harry
harry.index = ['first','second','third','fourth']
harry
ser = pd.Series(np.random.rand(34))
type(ser)
newdf = pd.DataFrame(np.random.rand(334,5),index = np.arange(334))
type(newdf)
newdf.head()
newdf.dtypes
newdf.describe()

newdf.dtypes
newdf.head()
newdf.index
newdf.columns
newdf.to_numpy()
newdf[0][0]= 0.3
newdf.head()
newdf.T
newdf.head()
newdf.sort_index(axis = 1,ascending=False)
newdf.head()
type(newdf[0])
newdf.columns = list("ABCDE")
newdf.head(2)
newdf.loc[[1,2],:]
newdf.loc[(newdf['A']<0.3)]
newdf.iloc[0,4]
newdf.iloc[[0,5],[0,3]]
newdf.head(3)
newdf.drop([0])
newdf.drop(['A'],axis = 1,inplace=True)
newdf
newdf.reset_index(drop = True,inplace=True)
newdf
newdf['B'].isnull()
newdf['B']=None
newdf
newdf.loc[:,['B']]
newdf
newdf.info()
newdf
data = {
    "Name": ["Alice", "Bob", "Alice", "David"],
    "Age": [25, 30, 25, 40],
    "City": ["NY", "LA", "NY", "Chicago"]
}
df.head()

import numpy as np
import pandas as pd
data = pd.DataFrame({
    "Name": ["Alice", "Bob", "Alice", "David"],
    "Age": [25, 30, 25, 40],
    "City": ["NAY", "LA", "NAY", "Chicago"]
})
data
data.dropna(how = 'all' , axis = 1)
data.drop_duplicates(subset = ['Name'],keep='first')
data.shape
data.info()
data['City'].value_counts(dropna=False)
df.notnull()

import numpy as np
import pandas as pd

data = {
    "Name": ["Harry", "Rohan", "Mohan", "Raghu"],
    "Marks": [92, 37, 28, 44],
    "City": ["Jaipur", "Jodhpur", "Churu", "Delhi"]
}

df = pd.DataFrame(data)
df
df.head()
df.tail()
df[["Name","Marks"]]
df["Marks"].max()
df["Marks"].mean()
df["Marks"].median()
df.loc[(df['Marks']>40)]
df.sort_index(axis = 1,ascending=False)
df.loc[[0,1],:]

import numpy as np
import pandas as pd
data = {
    "Name": ["A", "B", "C", "D", "E"],
    "Age": [20, 21, 19, 22, 20],
    "Marks": [85, 90, 78, 88, 95]
}

df = pd.DataFrame(data)
df.loc[0,'Grade']=None
df.head()
df.loc[0,"Pass"]=None
df["Pass"] = df["Marks"] >= 40
df
df = df["Age"]>=20
df
df = pd.DataFrame(data)
df
df.rename(columns={"Marks": "Score"}, inplace=True)
df
df.drop(['Age'],axis = 1,inplace = True)
df
df.loc[2,'Score']=80
df.head()
df.max()
df.min()
df.to_csv('students.csv')
df = pd.read_csv('students.csv')
df
df.loc[0,"Age"]=None
df
df.info()
df.describe()
df.isnull()
df.notnull()



from google.colab import drive
drive.mount('/content/drive')

"""# MATPLOTLIB

"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
from matplotlib import pyplot as plt
plt.plot([1,2,3] , [2,5,7])
plt.title("harry's data")
plt.xlabel("this is X")
plt.ylabel("this is Y")
plt.show()

from matplotlib import pyplot as plt
from matplotlib import style
style.use('ggplot')
x = [2,3,4]
y = [23,45,66]
x2 = [3,4,6]
y2 = [7,9,2]
plt.scatter(x,y , label = "first",linewidth = 5)
plt.hist(x2,label = "second")
plt.legend()
plt.show

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
# %matplotlib inline
from matplotlib import pyplot as plt
dataset = pd.read_csv("harry.csv")
dataset.head(3)

import numpy as np
import pandas as pd
dict1 = {
    "name":['harry','rohan','mohan','raghu'],
    "marks":[114,114,28,44],
    "city":['jaipur','jodhpur','churu','pakistan'],

}
df = pd.DataFrame(dict1)
df

df.to_csv('TRK.csv')

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
# %matplotlib inline
from matplotlib import pyplot as plt
dataset = pd.read_csv("TRK.csv")
dataset

np.mean(dataset["marks"])

np.median(dataset["marks"])

dataset["marks"].mode()
dataset["marks"].value_counts()

min_r = dataset["marks"].min()
max_r = dataset["marks"].max()
range = max_r - min_r
range

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
# %matplotlib inline
from matplotlib import pyplot as plt
sec_a = np.array([75,65,73,68,72,67])
sec_b = np.array([90,47,43,96,93,51])
mean = np.mean(sec_a)
mean

mad_a = np.sum(np.abs(sec_a - mean))/len(sec_a)
mad_b = np.sum(np.abs(sec_b - mean))/len(sec_b)
mad_a,mad_b

np.std(sec_a),np.std(sec_b)

np.var(sec_a) , np.var(sec_b)

# Commented out IPython magic to ensure Python compatibility.
from io import IncrementalNewlineDecoder
import pandas as pd
# %matplotlib inline
from matplotlib import pyplot as plt
from matplotlib import style
style.use('ggplot')
dataset = pd.read_csv("TRK.csv")
dataset

dataset.isnull()

dataset.info()

data_corr = dataset.select_dtypes("int64").corr()
data_corr

data_cov = dataset.select_dtypes("int64").cov()
data_cov

plt.figure(figsize = (4,5))
plt.hist(data_corr)
plt.show()

plt.figure(figsize = (4,5))
plt.hist(data_cov)
plt.show()

